# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  dev:
    cmds:
      - go run ./cmd/http/main.go
    silent: true
  
  swag:
    cmds:
      - swag init --generalInfo ./cmd/http/main.go --output ./docs --parseDependency --parseInternal
    silect: true
